### ISSUE TITLE
`frame.to_ndarray(format='rgba')` still cause a crash

### ISSUE THREAD

**Issue by laggykiller** [PyAV-Org/PyAV#1930]
Related issue: https://github.com/PyAV-Org/PyAV/issues/1269

https://github.com/user-attachments/assets/aae188fc-0707-44b4-872b-3e0b0ec07ade

```python
import av
from av.codec.context import CodecContext

in_f = '026.webm'
frames = []

context = CodecContext.create('libvpx-vp9', 'r')

with av.open(in_f) as container:
    for packet in container.demux(video=0):
        for frame in context.decode(packet):
            frame_nd = frame.to_ndarray(format='rgba') # Crash here
            frames.append(frame_nd)
```

Still results in crash:
```
malloc(): corrupted top size
Aborted (core dumped)
```

**Comment by WyattBlue** [comment]
Fixed, see: https://github.com/PyAV-Org/PyAV/discussions/1510

**Comment by laggykiller** [comment]
@WyattBlue No, the issue was **not** resolved, running the code above still crash. Tested on WIndows and Arch Linux, with av 16.1.0

**Comment by WyattBlue** [comment]
@laggykiller Test with master

**Comment by WyattBlue** [comment]
And if there's a crash. Put your architecture and platform. I tested with AArch64 macos and didn't get anything

**Comment by laggykiller** [comment]
Can confirm that it works on master, thank you.

**Comment by WyattBlue** [comment]
Thanks for confirming.
