### ISSUE TITLE
PyAv fails to install with pip in Python 3.10

### ISSUE THREAD

**Issue by WyattBlue** [PyAV-Org/PyAV#820]
Pip fails to install PyAv in Python 3.10, although previously installing correctly in Python 3.9 . I'm running macOS, but I suspect this is a problem on Windows and Linux as well.

The command I ran was:

```
pip3 install av
```

pip3 being 

<details>
  <summary>Building wheel output</summary>
  
```
Collecting av
  Using cached av-8.0.3.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: av
  Building wheel for av (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"'; __file__='"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-wheel-i6v5gwgz
       cwd: /private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.10
  creating build/lib.macosx-10.15-x86_64-3.10/av
  copying av/deprecation.py -> build/lib.macosx-10.15-x86_64-3.10/av
  copying av/datasets.py -> build/lib.macosx-10.15-x86_64-3.10/av
  copying av/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av
  copying av/__main__.py -> build/lib.macosx-10.15-x86_64-3.10/av
  creating build/lib.macosx-10.15-x86_64-3.10/av/video
  copying av/video/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/video
  creating build/lib.macosx-10.15-x86_64-3.10/av/codec
  copying av/codec/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/codec
  creating build/lib.macosx-10.15-x86_64-3.10/av/container
  copying av/container/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/container
  creating build/lib.macosx-10.15-x86_64-3.10/av/audio
  copying av/audio/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/audio
  creating build/lib.macosx-10.15-x86_64-3.10/av/subtitles
  copying av/subtitles/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/subtitles
  creating build/lib.macosx-10.15-x86_64-3.10/av/filter
  copying av/filter/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/filter
  creating build/lib.macosx-10.15-x86_64-3.10/av/sidedata
  copying av/sidedata/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/sidedata
  creating build/lib.macosx-10.15-x86_64-3.10/av/data
  copying av/data/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/data
  running build_ext
  running config
  PyAV: 8.0.3 (unknown commit)
  Python: 3.10.0 (default, Oct 13 2021, 06:44:31) [Clang 12.0.0 (clang-1200.0.32.29)]
  platform: macOS-10.15.7-x86_64-i386-64bit
  extension_extra:
  	include_dirs: [b'include', b'/usr/local/Cellar/ffmpeg/4.4_2/include']
  	libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
  	library_dirs: [b'/usr/local/Cellar/ffmpeg/4.4_2/lib']
  	define_macros: []
  	runtime_library_dirs: []
  config_macros:
  	PYAV_COMMIT_STR="unknown-commit"
  	PYAV_VERSION=8.0.3
  	PYAV_VERSION_STR="8.0.3"
  writing build/temp.macosx-10.15-x86_64-3.10/include/pyav/config.h
  running cythonize
  building 'av.plane' extension
  creating build/temp.macosx-10.15-x86_64-3.10/src
  creating build/temp.macosx-10.15-x86_64-3.10/src/av
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/Cellar/ffmpeg/4.4_2/include -I/usr/local/include -Ibuild/temp.macosx-10.15-x86_64-3.10/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Iinclude -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/temp.macosx-10.15-x86_64-3.10/include -c src/av/plane.c -o build/temp.macosx-10.15-x86_64-3.10/src/av/plane.o
  clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.10/src/av/plane.o -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib -L/usr/local/Cellar/ffmpeg/4.4_2/lib -L/usr/local/opt/sqlite/lib -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -lavfilter -lavutil -lswresample -lavcodec -lswscale -lavdevice -lavformat -o build/lib.macosx-10.15-x86_64-3.10/av/plane.cpython-310-darwin.so
  building 'av.dictionary' extension
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/Cellar/ffmpeg/4.4_2/include -I/usr/local/include -Ibuild/temp.macosx-10.15-x86_64-3.10/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Iinclude -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/temp.macosx-10.15-x86_64-3.10/include -c src/av/dictionary.c -o build/temp.macosx-10.15-x86_64-3.10/src/av/dictionary.o
  src/av/dictionary.c:5948:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^
  src/av/dictionary.c:5948:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/av/dictionary.c:5953:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^
  src/av/dictionary.c:5953:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/av/dictionary.c:6037:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, NULL);
                    ^
  src/av/dictionary.c:6037:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, NULL);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  3 warnings and 3 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for av

```
</details>

It then tries to build with setup.py, but also fails.

<details>
  <summary>Setup.py output</summary>

```
  Running setup.py clean for av
Failed to build av
Installing collected packages: av
    Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"'; __file__='"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-record-v2lev55f/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/av
         cwd: /private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/
    Complete output (70 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.10
    creating build/lib.macosx-10.15-x86_64-3.10/av
    copying av/deprecation.py -> build/lib.macosx-10.15-x86_64-3.10/av
    copying av/datasets.py -> build/lib.macosx-10.15-x86_64-3.10/av
    copying av/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av
    copying av/__main__.py -> build/lib.macosx-10.15-x86_64-3.10/av
    creating build/lib.macosx-10.15-x86_64-3.10/av/video
    copying av/video/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/video
    creating build/lib.macosx-10.15-x86_64-3.10/av/codec
    copying av/codec/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/codec
    creating build/lib.macosx-10.15-x86_64-3.10/av/container
    copying av/container/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/container
    creating build/lib.macosx-10.15-x86_64-3.10/av/audio
    copying av/audio/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/audio
    creating build/lib.macosx-10.15-x86_64-3.10/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/subtitles
    creating build/lib.macosx-10.15-x86_64-3.10/av/filter
    copying av/filter/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/filter
    creating build/lib.macosx-10.15-x86_64-3.10/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/sidedata
    creating build/lib.macosx-10.15-x86_64-3.10/av/data
    copying av/data/__init__.py -> build/lib.macosx-10.15-x86_64-3.10/av/data
    running build_ext
    running config
    PyAV: 8.0.3 (unknown commit)
    Python: 3.10.0 (default, Oct 13 2021, 06:44:31) [Clang 12.0.0 (clang-1200.0.32.29)]
    platform: macOS-10.15.7-x86_64-i386-64bit
    extension_extra:
    	include_dirs: [b'include', b'/usr/local/Cellar/ffmpeg/4.4_2/include']
    	libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
    	library_dirs: [b'/usr/local/Cellar/ffmpeg/4.4_2/lib']
    	define_macros: []
    	runtime_library_dirs: []
    config_macros:
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_VERSION=8.0.3
    	PYAV_VERSION_STR="8.0.3"
    writing build/temp.macosx-10.15-x86_64-3.10/include/pyav/config.h
    running cythonize
    building 'av.plane' extension
    creating build/temp.macosx-10.15-x86_64-3.10/src
    creating build/temp.macosx-10.15-x86_64-3.10/src/av
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -I/usr/local/opt/openssl@1.1/include -Ibuild/temp.macosx-10.15-x86_64-3.10/include -I/usr/local/include -Iinclude -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/ffmpeg/4.4_2/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/temp.macosx-10.15-x86_64-3.10/include -c src/av/plane.c -o build/temp.macosx-10.15-x86_64-3.10/src/av/plane.o
    clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.10/src/av/plane.o -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib -L/usr/local/Cellar/ffmpeg/4.4_2/lib -L/usr/local/opt/sqlite/lib -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -lavutil -lavcodec -lswresample -lswscale -lavdevice -lavfilter -lavformat -o build/lib.macosx-10.15-x86_64-3.10/av/plane.cpython-310-darwin.so
    building 'av.dictionary' extension
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -I/usr/local/opt/openssl@1.1/include -Ibuild/temp.macosx-10.15-x86_64-3.10/include -I/usr/local/include -Iinclude -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/ffmpeg/4.4_2/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/temp.macosx-10.15-x86_64-3.10/include -c src/av/dictionary.c -o build/temp.macosx-10.15-x86_64-3.10/src/av/dictionary.o
    src/av/dictionary.c:5948:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^
    src/av/dictionary.c:5948:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/av/dictionary.c:5953:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^
    src/av/dictionary.c:5953:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/av/dictionary.c:6037:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = _PyGen_Send((PyGenObject*)yf, NULL);
                      ^
    src/av/dictionary.c:6037:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                ret = _PyGen_Send((PyGenObject*)yf, NULL);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings and 3 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"'; __file__='"'"'/private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-install-ueuk0jey/av_8390aa79b33c4620ba45138c42abf523/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zq/hdpr7cks7tng18nrkd9v8qv80000gn/T/pip-record-v2lev55f/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/av Check the logs for full command output.
```
</details>

## Investigation

Python 3.10 wheels are not provided in [PyPI](https://pypi.org/project/av/#files), providing them should help.

## Research

I have done the following:

- [x] Checked the [PyAV documentation](https://pyav.org/docs)
- [x] Searched on [Google](https://www.google.com/search?q=pyav+how+do+I+foo)
- [x] Searched on [Stack Overflow](https://stackoverflow.com/search?q=pyav)
- [x] Looked through [old GitHub issues](https://github.com/PyAV-Org/PyAV/issues?&q=is%3Aissue)
- [ ] Asked on [PyAV Gitter](https://gitter.im/PyAV-Org)
- [ ] ... and waited 72 hours for a response.

**Comment by WyattBlue** [comment]
Current finding for 3.10:



|           | Windows |   MacOS   |   Linux |
| :---- | :---------: | :--------: | :-----: |
| Python.org | ❌ |   ❌  |   ? |
| Pyenv | ? | ❌ |   ✅ |
| choco/brew/pacman | ?  |  ❌  | not available |

**Comment by jlaine** [comment]
Right, there are no published Python 3.10 wheels for PyAV ATM.

**Comment by WyattBlue** [comment]
> Right, there are no published Python 3.10 wheels for PyAV ATM.

@jlaine can we get an ETA on this? 

Also would it be possible to build the wheels without requiring any particular Python version? That way, pyav would still work even if a new minor version was patched.

**Comment by samdbmg** [comment]
> I tried it with Python3.10 on Linux with building Python from source, and while python3.10 -m pip install av --no-binary av did exit with a code 0. When I tried to import av, it threw this import error:

I had a play with this a few months ago, and AIUI that's caused by https://github.com/cython/cython/issues/3876 - the tl;dr is you need a newer Cython to work with Python 3.10.

You should find if you build PyAV from the repo (not the sdist) and have a suitable ffmpeg installed it will work on Python 3.10, either using the instructions at https://pyav.org/docs/stable/overview/installation.html#via-source or cloning the repo and something like `pip3 install Cython && make && python3 setup.py install`

**Comment by samdbmg** [comment]
@jlaine I also had a go at replicating your CI process to try and build wheels for 3.10 with ffmpeg included, and ran into a problem like the below (see https://gist.github.com/samdbmg/ec360c4e6ce70c37214063c5148cb0f3 for the full output)

```
<snip lots of similar lines>
DEBUG:auditwheel.policy.versioned_symbols:Package requires ZLIB_1.2.9, incompatible with policy manylinux_2_24_x86_64 which requires {'ZLIB_1.2.3.4', 'ZLIB_1.2.3.5', 'ZLIB_1.2.0', 'ZLIB_1.2.5.1', 'ZLIB_1.2.2', 'ZLIB_1.2.2.4', 'ZLIB_1.2.3.3', 'ZLIB_1.2.5.2', 'ZLIB_1.2.2.3', 'ZLIB_1.2.0.8', 'ZLIB_1.2.0.2'}
DEBUG:auditwheel.policy.versioned_symbols:Package requires GLIBC_2.14, incompatible with policy manylinux_2_5_x86_64 which requires {'GLIBC_2.2.6', 'GLIBC_2.5', 'GLIBC_2.3.3', 'GLIBC_2.3.2', 'GLIBC_2.3', 'GLIBC_2.3.4', 'GLIBC_2.2.5', 'GLIBC_2.4'}
DEBUG:auditwheel.policy.versioned_symbols:Package requires GLIBC_2.14, incompatible with policy manylinux_2_12_x86_64 which requires {'GLIBC_2.9', 'GLIBC_2.11', 'GLIBC_2.7', 'GLIBC_2.2.6', 'GLIBC_2.5', 'GLIBC_2.6', 'GLIBC_2.3.3', 'GLIBC_2.3.2', 'GLIBC_2.3', 'GLIBC_2.3.4', 'GLIBC_2.8', 'GLIBC_2.2.5', 'GLIBC_2.12', 'GLIBC_2.10', 'GLIBC_2.4'}
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "/tmp/cibuildwheel/built_wheel/av-8.0.3-cp310-cp310-linux_x86_64.whl" to "manylinux2014_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```

I think that's caused by auditwheel now insisting those checks pass, whereas the version bundled with cibuildwheel<2.0.0 emitted the warnings but produced the wheel anyway (but is too old to support py3.10). Unfortunately I don't understand enough about what's going on to be able to fix that!

**Comment by WyattBlue** [comment]
> You should find if you build PyAV from the repo (not the sdist) and have a suitable ffmpeg installed it will work on Python 3.10, either using the instructions at https://pyav.org/docs/stable/overview/installation.html#via-source or cloning the repo and something like `pip3 install Cython && make && python3 setup.py install`

I can confirm this works.

**Comment by christophfink** [comment]
> You should find if you build PyAV from the repo (not the sdist) and have a suitable ffmpeg installed it will work on Python 3.10, either using the instructions at https://pyav.org/docs/stable/overview/installation.html#via-source or cloning the repo and something like pip3 install Cython && make && python3 setup.py install

Works over here, too. Any idea what can be done to make the sdist work? (I’m on Cython 0.29.26, the bug @samdbmg linked to supposedly has been fixed in 0.29.22)

**Comment by Broekman** [comment]
Thanks for the updates all.

Using Cython 0.29.26, ffmpeg 2:4.4.1 and building the repo from source (latest), I still get this _PyGen_Send import error on (Arch) Linux. Any ideas?

**Comment by jlaine** [comment]
I'd be happy to roll out Python 3.10 wheels, but the problem I have is that the build process is currently broken due to lack of up-to-date binaries for FFmpeg.

The pyav-ffmpeg repo provides binaries of the FFmpeg libraries for our different platforms. Linux + OS X are built from source, which is great: we can track FFmpeg releases. Building FFmpeg from source for Windows is very tricky, and we relied on third-party builds, which have unfortunately been discontinued.

If anyone wants to help out, the action will be in pyav-ffmpeg: provide a pull request which allows building FFmpeg (and all its dependencies) from source, in line with what's done for the other platforms.

**Comment by jlaine** [comment]
I have just tagged release 8.1.0, as soon as CI completes it will upload wheels for Python 3.10 to PyPI. 🎉

**Comment by C-o-l-u-m-b-o** [comment]
echo "cython<3.0" >> c.txt
PIP_CONSTRAINT=c.txt pip install av==10.0.0

(if you want install av version 10.0.0)

if you are on Windows use Powershell (or terminal in VS code), instead of PIP_CONSTRAINT=c.txt 
before you call pip install, do 
$env:PIP_CONSTRAINT='c.txt.' and press enter
then
pip install av==10.0.0
